#!/bin/sh

compile() {
    # Convert all plain-text links to HTML links (<a href="X">X</a>).
    sed -E "s|([^\"\'\>=])(http[s]?://[^[:space:]]*)|\1<a href=\2>\2</a>|g
            s|^(http[s]?://[^[:space:]]*)|<a href=\1>\1</a>|g" |

    # Convert #/words to local links.
    # Convert @/words to external HTML links.
    sed -E "s|(#/)([^ \)]*)|\1<a href=/\2>\2</a>|g
            s|(@/)([^ \)]*)|\1<a href=http://\2>\2</a>|g" |

    # Convert [0-9] into HTML links.
    sed -E "s|^([ -]*)\[([0-9\.]*)\]|\1<span id=\2>[\2]</span>|g
            s|([^\"#])\[([0-9\.]*)\]|\1[<a class=t href=#\2>\2</a>]|g" |

    # Insert the page into the template.
    sed -E '/%%CONTENT%%/{r /dev/stdin
            d;}' template.html |

    # Insert the page path into the source URL.
    sed -E "s	%%TITLE%%	${1:-microwa.re}	"
}

page() {
  t=${1#.}
  t=${t%%.txt}
  t=${t%%/index}
  t=${t##*/}

  p=${1%%.txt}
  p=${p#.}
  test "${p##*/}" != "index" && p=$p/index
  
  d=${p%/*}
  mkdir -p docs$d

  case $1 in
  *.txt)
    compile "$t" < "src/$1" > "docs$p.html";;
  *)
  cp -Lf "src/$1" "docs/$1";;
  esac
  
}

pad() {
  n=$((80-$(echo "$1$2"|wc -m)-1))
  printf "$1$(i=0;while test $i -le $n; do i=$((i+1));printf "-";done)$2\n"
}

blog(){
  find $1 ! -type d|while read -r f; do
    p=${f##$1}
    p=${p%.txt}
    p=${p%/index}
    
    test "$p" = "index"||pad "* $(sed 's/ .*$//;q' $f) " " #/blog/$p/"
  done
}

main() {
  rm -rf docs/*
  mkdir -p docs

  blog src/blog/ > src/blog/index.txt
  
  (cd src/&&find . ! -type d) | while read -r page; do
    printf "$page\n"
    page "$page"
  done

  cp 404.html docs/
  cp CNAME docs/
}

main "$@"